### PR TITLE
Update to Swift 4.2

### PR DESCRIPTION
**Pull request by SpectralDragon**
This change is [Reviewable](https://reviewable.io/reviews/alexruperez/speechrecognizerbutton/3)

### CODE REVIEW

**Comment by SpectralDragon** [comment]
Travis get fail, because `Travis CI` used Swift 4.0 and Xcode 9.4.1

**Comment by alexruperez** [comment]
Please @SpectralDragon, update .travis.yml to:
...
osx_image: **xcode10**
script:
\- xcodebuild -workspace SpeechRecognizerButton.xcworkspace -scheme Example -destination "platform=iOS Simulator,name=**iPhone XS,OS=12.0**" -configuration Debug -enableCodeCoverage YES clean build test
...
Thanks!

**Comment by SpectralDragon** [comment]
Okay, I did update Travis config :)

**Review by alexruperez — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/alexruperez/speechrecognizerbutton/3)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by alexruperez** [comment]
@SpectralDragon release ready https://cocoapods.org/pods/SpeechRecognizerButton

**Pull request merged**
